baseURL = 'https://zengbs.github.io/'
languageCode = 'en-US'
title = 'C++ notes'
theme = "" # 留空，我們不使用外部主題

# --- 核心設定：程式碼語法高亮 (Chroma) ---
[markup]
  [markup.highlight]
    codeFences = true      # 支援 ```c++ 這種語法
    guessSyntax = true     # 如果沒寫語言，Hugo 會嘗試猜測
    lineNos = true         # 顯示行號 (看 C++ 程式碼很需要)
    style = "monokai"      # 程式碼區域的配色。
                           # "monokai" 是經典深色背景，
                           # 如果你連程式碼區都要白底，可用 "bw" (Black/White) 或 "pygments"。
    noClasses = true       # 為了方便，我們直接把 CSS 寫入 HTML，不需要額外的 CSS 檔案。
